# 100 numpy exercises (Optional)

Source: https://github.com/rougier/numpy-100


#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [3]:
np.version.version

'1.24.2'

#### 3. Create a null vector of size 10 (★☆☆)

In [4]:
vector = np.zeros(10)

#### 4. How to find the memory size of any array (★☆☆)

In [5]:
vector.itemsize

8

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [6]:
vector = np.arange(10,50)
vector

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [7]:
vector[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [8]:
vector = np.arange(0,9)
matrix = np.reshape(vector, (3,3))
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [9]:
array = [1,2,0,0,4,0]
np.nonzero(array)

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [10]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [11]:
np.random.randn(3,3,3)

array([[[ 0.9917929 , -0.43926722, -0.68681142],
        [-0.54103754,  0.19117979, -1.19874998],
        [-1.7692977 , -0.82969943,  0.36689952]],

       [[-0.56783704, -1.49789589, -0.55397222],
        [-0.7145083 ,  0.10496228, -0.00270118],
        [ 0.04392912,  0.50146852,  0.29477207]],

       [[-1.00297764,  1.74653753, -1.13402258],
        [ 0.59398942,  0.2236074 , -0.22822275],
        [ 2.5628662 , -1.91803503,  1.28622548]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [12]:
matrix = np.random.randn(10,10)
min, max = matrix.min(), matrix.max()
print(min, max)

-2.270001418037653 3.327743318628795


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [13]:
vector = np.random.randn(30,)
np.mean(vector)

-0.058044360706481696

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [14]:
matrix = np.zeros((4,4))
matrix[0,:] = 1
matrix[-1,:] = 1
matrix[:,0] = 1
matrix[:,-1] = 1
matrix

array([[1., 1., 1., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [15]:
matrix = np.ones((5,5))
np.pad(matrix, pad_width=1, mode='constant', constant_values=0)

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [16]:
np.diag(1+np.arange(4), k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [17]:
matrix = np.zeros((8,8),dtype=int)
matrix[1::2,::2] = 1
matrix[::2,1::2] = 1
matrix

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [18]:
print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [25]:
array = np.array([[0,1],[1,0]])
np.tile(array, (4,4))


array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [14]:
Z = np.random.random((5,5))
Z = (Z - np.mean (Z)) / (np.std (Z))
print(Z)

[[-0.46299451 -0.76084741  1.47116498  0.184287   -0.99387726]
 [-1.4699343   0.39032376 -0.72816178  1.29555718  0.5978739 ]
 [-1.02962352  1.33322095 -1.52622362  0.74362548 -1.20129745]
 [-1.03988513  0.71242342  1.29673825  1.58162511  0.5577387 ]
 [ 0.87329326 -0.56375296  0.44238387 -1.14163492 -0.56202302]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [16]:
color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [23]:
a = np.ones((5,3))
b = np.ones((3,2))
np.matmul(a,b)

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [26]:
vector = np.ones((10,))
vector[3:9] *= -1
print(vector)

[ 1.  1.  1. -1. -1. -1. -1. -1. -1.  1.]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [29]:
print(sum(range(5),-1))

9
range(0, 5)


#### 29. How to round away from zero a float array ? (★☆☆)

In [40]:
matrix = np.random.uniform(-10,+10,10)
print(matrix)
np.copysign(np.ceil(np.abs(matrix)), matrix)

[ 9.6011406  -7.24414299  2.26992081  0.6095899  -5.73499973 -1.73956589
 -4.60237252 -4.54560039  1.20021789 -8.10502203]


array([10., -8.,  3.,  1., -6., -2., -5., -5.,  2., -9.])

#### 30. How to find common values between two arrays? (★☆☆)

In [44]:
a = np.arange(1,7)
b = np.arange(3,10)
np.intersect1d(a,b)

array([3, 4, 5, 6])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [45]:
# Suicide mode on
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

# Back to sanity
_ = np.seterr(**defaults)

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [51]:
y = np.datetime64('today') - np.timedelta64(1)
t = np.datetime64('today')
d = np.datetime64('today') + np.timedelta64(1)
print(y,t,d)

2023-12-25 2023-12-26 2023-12-27


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [52]:
np.arange('2023-12', '2024-01', dtype='datetime64[D]')

array(['2023-12-01', '2023-12-02', '2023-12-03', '2023-12-04',
       '2023-12-05', '2023-12-06', '2023-12-07', '2023-12-08',
       '2023-12-09', '2023-12-10', '2023-12-11', '2023-12-12',
       '2023-12-13', '2023-12-14', '2023-12-15', '2023-12-16',
       '2023-12-17', '2023-12-18', '2023-12-19', '2023-12-20',
       '2023-12-21', '2023-12-22', '2023-12-23', '2023-12-24',
       '2023-12-25', '2023-12-26', '2023-12-27', '2023-12-28',
       '2023-12-29', '2023-12-30', '2023-12-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [53]:
A = np.ones(3)*1
B = np.ones(3)*2
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [54]:
Z = np.random.uniform(0,10,10)

print(Z - Z%1)
print(Z // 1)
print(np.floor(Z))
print(Z.astype(int))
print(np.trunc(Z))

[0. 7. 5. 6. 7. 3. 9. 1. 7. 3.]
[0. 7. 5. 6. 7. 3. 9. 1. 7. 3.]
[0. 7. 5. 6. 7. 3. 9. 1. 7. 3.]
[0 7 5 6 7 3 9 1 7 3]
[0. 7. 5. 6. 7. 3. 9. 1. 7. 3.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [59]:
array = [i % 5 for i in range(25)]
print(array)
matrix = np.array(array).reshape((5,5))
print(matrix)

np.tile(np.arange(0, 5), (5,1))

[0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4]
[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [65]:
np.linspace(0,1,11,False)[1:]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [68]:
vector = np.random.randn(10)
print(vector)
np.sort(vector)

[-1.22438153 -0.21604468 -0.8823978   0.67973223  1.79531919  1.85711014
 -0.61840663 -0.44467803  0.80022711  0.57790249]


array([-1.22438153, -0.8823978 , -0.61840663, -0.44467803, -0.21604468,
        0.57790249,  0.67973223,  0.80022711,  1.79531919,  1.85711014])

#### 41. How to sum a small array faster than np.sum? (★★☆)

In [75]:
Z = np.arange(10)
sum = np.add.reduce(Z)
print(sum)


45


#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [76]:
a = np.arange(5)
b = np.arange(5)
np.allclose(a,b)

True

#### 43. Make an array immutable (read-only) (★★☆)

In [77]:
np.arange(5).flags.writeable = False

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [79]:
coord = np.random.randn(10,2)
print(coord)

[[-0.48587422 -0.73030003]
 [ 0.58191743  2.65437572]
 [ 1.09292893 -0.53487112]
 [ 0.7731846  -0.42441554]
 [ 1.16835801 -0.60833335]
 [ 0.13134879 -0.31338454]
 [ 0.82801026 -0.67045843]
 [-0.44458837 -1.18731484]
 [ 0.20847402 -0.01975134]
 [-0.90497664  0.39813299]]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [7]:
vector = np.random.randn(10,)
vector[vector.argmax()] = 0
print(vector)

[ 0.04480325 -0.06389463  0.         -0.89386739 -0.32892673 -0.04450415
 -1.04065637 -0.50146081  1.09274772 -0.26464019]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [11]:
grid = np.zeros((5,5), dtype=[('X', 'float'), ('Y', 'float')])
print(grid)
grid['X'], grid['Y'] = np.meshgrid(np.linspace(0,1,5),np.linspace(0,1,5))
print(grid)

[[(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]]
[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

In [19]:
x = np.array([1,2,3,4])
y = np.array([5,6,7,8]).reshape(-1,1)
print(x,y)
c = 1.0 / (x - y)
print(c)

[1 2 3 4] [[5]
 [6]
 [7]
 [8]]
[[-0.25       -0.33333333 -0.5        -1.        ]
 [-0.2        -0.25       -0.33333333 -0.5       ]
 [-0.16666667 -0.2        -0.25       -0.33333333]
 [-0.14285714 -0.16666667 -0.2        -0.25      ]]


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [29]:
np.zeros(10, [ ('position', [ ('x', float),
                                  ('y', float)]),
                   ('color',    [ ('r', np.int8),
                                  ('g', np.int8),
                                  ('b', np.int8)])])

array([((0., 0.), (0, 0, 0)), ((0., 0.), (0, 0, 0)),
       ((0., 0.), (0, 0, 0)), ((0., 0.), (0, 0, 0)),
       ((0., 0.), (0, 0, 0)), ((0., 0.), (0, 0, 0)),
       ((0., 0.), (0, 0, 0)), ((0., 0.), (0, 0, 0)),
       ((0., 0.), (0, 0, 0)), ((0., 0.), (0, 0, 0))],
      dtype=[('position', [('x', '<f8'), ('y', '<f8')]), ('color', [('r', 'i1'), ('g', 'i1'), ('b', 'i1')])])

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [30]:
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

[[0.         0.29313111 0.8606079  0.82166536 0.57717713 0.82264581
  0.49575677 0.62642833 0.76488891 0.27623716]
 [0.29313111 0.         0.61819821 0.60526637 0.50020845 0.57564637
  0.25532547 0.40597421 0.64812373 0.16281108]
 [0.8606079  0.61819821 0.         0.10591869 0.47906952 0.77592809
  0.67707389 0.76691211 0.40025588 0.76732369]
 [0.82166536 0.60526637 0.10591869 0.         0.38636058 0.84144485
  0.70363712 0.80915991 0.29446275 0.76266848]
 [0.57717713 0.50020845 0.47906952 0.38636058 0.         0.9769174
  0.71757713 0.86245931 0.19361084 0.65332933]
 [0.82264581 0.57564637 0.77592809 0.84144485 0.9769174  0.
  0.32867341 0.20522392 1.04823793 0.5490584 ]
 [0.49575677 0.25532547 0.67707389 0.70363712 0.71757713 0.32867341
  0.         0.15140803 0.83215474 0.2279979 ]
 [0.62642833 0.40597421 0.76691211 0.80915991 0.86245931 0.20522392
  0.15140803 0.         0.96607732 0.3504031 ]
 [0.76488891 0.64812373 0.40025588 0.29446275 0.19361084 1.04823793
  0.83215474 0.966077

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [34]:
Z = (np.random.rand(10)*100).astype(np.float32)
print(Z)
Y = Z.view(np.int32)
Y[:] = Z
print(Y)

[39.377693 92.73837  44.29931  67.39486  71.75096  70.34074  50.063213
 39.74229  14.786439 95.07118 ]
[39 92 44 67 71 70 50 39 14 95]


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [39]:
array = np.array([1,2,3,4,5])
for index, x in np.ndenumerate(array):
    print(index, x)
for index in np.ndindex(array.shape):
    print(index, array[index])

(0,) 1
(1,) 2
(2,) 3
(3,) 4
(4,) 5
(0,) 1
(1,) 2
(2,) 3
(3,) 4
(4,) 5


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [49]:
x, y = np.meshgrid(np.linspace(0,100,10), np.linspace(0,100,10))
a = np.sqrt(x*x+y*y)
sigma, mu = 1.0, 0.0
np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )

array([[1.        , 0.95794691, 0.69051128, 0.71350418, 0.84656633,
        0.71292927, 0.88436325, 0.82184273, 0.74637471, 0.96256519],
       [0.95794691, 1.        , 0.82606277, 0.83262352, 0.88240491,
        0.84731363, 0.96792996, 0.92089659, 0.81055816, 0.98683372],
       [0.69051128, 0.82606277, 1.        , 0.99440632, 0.89158562,
        0.74005394, 0.79515793, 0.74521904, 0.92302184, 0.74498379],
       [0.71350418, 0.83262352, 0.99440632, 1.        , 0.92808009,
        0.70186464, 0.78070916, 0.72081708, 0.9575722 , 0.74764157],
       [0.84656633, 0.88240491, 0.89158562, 0.92808009, 1.        ,
        0.62052847, 0.77301373, 0.68941075, 0.98143197, 0.8078171 ],
       [0.71292927, 0.84731363, 0.74005394, 0.70186464, 0.62052847,
        1.        , 0.94741969, 0.97916175, 0.57729529, 0.86007768],
       [0.88436325, 0.96792996, 0.79515793, 0.78070916, 0.77301373,
        0.94741969, 1.        , 0.98860324, 0.70734217, 0.97434335],
       [0.82184273, 0.92089659, 0.7452190

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [62]:
array = np.arange(9).reshape(3,3)
np.put(array, np.random.choice(range(9), 3, replace=True), 1)
array

array([[0, 1, 2],
       [3, 1, 5],
       [1, 1, 8]])

#### 58. Subtract the mean of each row of a matrix (★★☆)

In [3]:
X = np.random.rand(5, 10)
Y = X - X.mean(axis=1, keepdims=True)

array([[-0.21197974, -0.17565655,  0.1227549 , -0.42825694,  0.03914225,
        -0.15426152,  0.22888262,  0.22789571,  0.34480365,  0.00667562],
       [ 0.1256747 , -0.34952963, -0.05548249, -0.32577261,  0.26332633,
        -0.0468886 , -0.37867214,  0.3273954 ,  0.17326856,  0.26668049],
       [-0.39224815, -0.19341166, -0.14855532,  0.21600597,  0.33605726,
         0.00901148,  0.40301863,  0.00644604,  0.18171657, -0.41804081],
       [ 0.21917351, -0.37907039, -0.21121818,  0.09539744,  0.03442802,
        -0.01405315, -0.10273521,  0.41120127,  0.29294264, -0.34606596],
       [-0.33009368, -0.42366196, -0.21052705, -0.20768139,  0.4597924 ,
        -0.21513228,  0.24742654,  0.11836451,  0.07179742,  0.48971548]])

#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [10]:
Z = np.random.randint(0,3,(3,10))
print(Z)
print((~Z.any(axis=0)).any())

[[2 0 0 1 2 0 2 1 1 2]
 [2 1 2 0 0 2 1 2 2 1]
 [2 0 1 0 0 1 2 1 1 1]]
True


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [11]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [15]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
print(I)
Z += np.bincount(I, minlength=len(Z))
print(Z)

[1 3 1 2 7 1 7 2 9 0 3 5 7 5 9 2 4 4 9 4]
[2. 4. 4. 3. 4. 3. 1. 4. 1. 4.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

Save and commit your work

In [ ]:
import jovian

In [ ]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "aakashns/numpy-100-exercises" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/aakashns/numpy-100-exercises


'https://jovian.ml/aakashns/numpy-100-exercises'

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

Save and commit your work.

In [ ]:
import jovian

In [ ]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "aakashns/numpy-100-exercises" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/aakashns/numpy-100-exercises


'https://jovian.ml/aakashns/numpy-100-exercises'

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

Save and commit your work

In [ ]:
import jovian

In [ ]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "aakashns/numpy-100-exercises" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/aakashns/numpy-100-exercises


'https://jovian.ml/aakashns/numpy-100-exercises'

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

Save and commit your work

In [ ]:
import jovian

In [ ]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..


Congratulations on completing the 100 exercises, well done!

#### What to do next?

- Share your completed notebook on Facebook, LinkedIn or Twitter and challenge your friends.
- Share your solutions and help others on the forum: https://jovian.ml/forum/t/100-numpy-exercises-hints-discussions-help/10561
- Check out our course on "Data Analysis with Python: Zero to Pandas" - https://jovian.ml/learn/data-analysis-with-python-zero-to-pandas
- Star this repository to show your appreciation for the original author of this notebook: https://github.com/rougier/numpy-100