In [1]:
import numpy as np

In [3]:
a = np.random.randint(0,10, [3,3])
print(a)
print(a.sum(axis=0))
print(a.sum(axis=1))

[[9 5 1]
 [1 9 4]
 [2 7 3]]
[12 21  8]
[15 14 12]


In [5]:
a = np.random.randint(0,10, [3,3])
print(a)
print(a.argsort())

[[7 5 3]
 [4 4 1]
 [0 8 1]]
[[2 1 0]
 [2 0 1]
 [0 2 1]]


In [7]:
a = np.random.randint(0,10, [3,3])
print(a)
print(a.mean())
print(a.std())
print(a.var())

[[5 1 2]
 [3 0 8]
 [2 0 7]]
3.111111111111111
2.7666443551086073
7.654320987654322


In [9]:
a = np.random.randint(0,10, [3,3])
print(a)
np.corrcoef(a)

[[7 8 3]
 [7 1 9]
 [6 2 9]]


array([[ 1.        , -0.81705717, -0.9148074 ],
       [-0.81705717,  1.        ,  0.98031562],
       [-0.9148074 ,  0.98031562,  1.        ]])

In [42]:
a = np.random.randint(0,10, [5,5])
print(a)
values, counts = np.unique(a, return_counts=True)
for i, j in zip(values[counts.argsort()], counts[counts.argsort()]):
    print(f'{i} apparait {j} fois')

[[5 4 7 2 8]
 [3 7 2 0 3]
 [4 2 0 3 8]
 [7 7 7 4 3]
 [2 3 5 0 4]]
5 apparait 2 fois
8 apparait 2 fois
0 apparait 3 fois
2 apparait 4 fois
4 apparait 4 fois
3 apparait 5 fois
7 apparait 5 fois


### NaN correction

In [47]:
a = np.random.randn(5,5)
a[1,2] = np.nan
a[4,3] = np.nan
a

[[ 0.77714593 -0.9360333   1.22205565  0.4285655   0.38140037]
 [-0.36048537  0.1502724          nan  0.15314391 -0.9548328 ]
 [ 0.99346694 -0.79382417 -1.21944524  0.86467017  0.41443916]
 [ 0.37437382  0.02855251 -1.02350941 -0.21351868  0.33569926]
 [-0.39342077  0.0326982   0.15194088         nan  1.67610267]]
[[False False False False False]
 [False False  True False False]
 [False False False False False]
 [False False False False False]
 [False False False  True False]]


0.09084598484649846

In [48]:
np.isnan(a)

array([[False, False, False, False, False],
       [False, False,  True, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False,  True, False]])

In [50]:
np.nanmean(a)

0.09084598484649846

In [51]:
a[np.isnan(a)] = 0
a

array([[ 0.77714593, -0.9360333 ,  1.22205565,  0.4285655 ,  0.38140037],
       [-0.36048537,  0.1502724 ,  0.        ,  0.15314391, -0.9548328 ],
       [ 0.99346694, -0.79382417, -1.21944524,  0.86467017,  0.41443916],
       [ 0.37437382,  0.02855251, -1.02350941, -0.21351868,  0.33569926],
       [-0.39342077,  0.0326982 ,  0.15194088,  0.        ,  1.67610267]])

### Algèbre linéaire

In [52]:
a = np.ones((2,3))
b = np.ones((3,2))
a, b

(array([[1., 1., 1.],
        [1., 1., 1.]]),
 array([[1., 1.],
        [1., 1.],
        [1., 1.]]))

In [53]:
a.T

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [58]:
c = np.random.randint(0,10, [3,3])
print(c)
np.linalg.det(c)

[[8 4 5]
 [2 8 4]
 [6 8 8]]


127.99999999999997

In [59]:
np.linalg.inv(c)

array([[ 0.25    ,  0.0625  , -0.1875  ],
       [ 0.0625  ,  0.265625, -0.171875],
       [-0.25    , -0.3125  ,  0.4375  ]])

In [60]:
np.linalg.eig(c)

(array([17.41746664,  5.15767811,  1.42485525]),
 array([[-0.55842422, -0.79350924, -0.39867041],
        [-0.42195488,  0.60755315, -0.38508325],
        [-0.71422439, -0.03496079,  0.83232974]]))

In [116]:
np.random.seed(0)
a = np.random.randint(0, 100, [10,5])
a

array([[44, 47, 64, 67, 67],
       [ 9, 83, 21, 36, 87],
       [70, 88, 88, 12, 58],
       [65, 39, 87, 46, 88],
       [81, 37, 25, 77, 72],
       [ 9, 20, 80, 69, 79],
       [47, 64, 82, 99, 88],
       [49, 29, 19, 19, 14],
       [39, 32, 65,  9, 57],
       [32, 31, 74, 23, 35]])

In [117]:
b = (a - np.mean(a,axis=0)) / np.std(a, axis=0)
b

array([[-0.02206157,  0.        ,  0.13173823,  0.72539252,  0.10755798],
       [-1.56637126,  1.61579632, -1.48676006, -0.33034307,  0.96802178],
       [ 1.12513992,  1.84021247,  1.03508612, -1.14768676, -0.27965074],
       [ 0.90452425, -0.35906585,  0.99744662,  0.0102168 ,  1.01104497],
       [ 1.6104944 , -0.44883231, -1.33620208,  1.0659524 ,  0.32267393],
       [-1.56637126, -1.21184724,  0.73397016,  0.7935045 ,  0.62383626],
       [ 0.11030784,  0.76301493,  0.80924915,  1.81518411,  1.01104497],
       [ 0.1985541 , -0.80789816, -1.56203905, -0.90929485, -2.17267111],
       [-0.24267724, -0.67324847,  0.16937773, -1.24985473, -0.32267393],
       [-0.55153918, -0.7181317 ,  0.50813319, -0.77307091, -1.26918412]])

In [118]:
b.mean(axis=0)

array([-2.22044605e-17, -4.44089210e-17,  0.00000000e+00, -1.22124533e-16,
       -4.44089210e-17])

In [119]:
b.std(axis=0)

array([1., 1., 1., 1., 1.])