In [1]:
import numpy as np

In [2]:
a = np.random.randint(0,10, [3,3])
print(a)
print(a.sum(axis=0))
print(a.sum(axis=1))

[[1 7 2]
 [6 6 5]
 [5 9 4]]
[12 22 11]
[10 17 18]


In [3]:
a = np.random.randint(0,10, [3,3])
print(a)
print(a.argsort())

[[8 7 4]
 [7 3 7]
 [1 6 2]]
[[2 1 0]
 [1 0 2]
 [0 2 1]]


In [4]:
a = np.random.randint(0,10, [3,3])
print(a)
print(a.mean())
print(a.std())
print(a.var())

[[0 3 7]
 [5 2 3]
 [6 7 7]]
4.444444444444445
2.4088314876309775
5.802469135802468


In [5]:
a = np.random.randint(0,10, [3,3])
print(a)
np.corrcoef(a)

[[5 7 5]
 [9 9 7]
 [7 2 8]]


array([[ 1.        ,  0.5       , -0.98782916],
       [ 0.5       ,  1.        , -0.62861856],
       [-0.98782916, -0.62861856,  1.        ]])

In [6]:
a = np.random.randint(0,10, [5,5])
print(a)
values, counts = np.unique(a, return_counts=True)
for i, j in zip(values[counts.argsort()], counts[counts.argsort()]):
    print(f'{i} apparait {j} fois')

[[4 0 4 2 8]
 [8 3 6 1 8]
 [3 9 2 1 8]
 [2 8 8 4 8]
 [2 2 2 5 9]]
0 apparait 1 fois
5 apparait 1 fois
6 apparait 1 fois
1 apparait 2 fois
3 apparait 2 fois
9 apparait 2 fois
4 apparait 3 fois
2 apparait 6 fois
8 apparait 7 fois


### NaN correction

In [7]:
a = np.random.randn(5,5)
a[1,2] = np.nan
a[4,3] = np.nan
a

array([[ 0.90372471,  1.4731846 , -0.57945294, -0.56177974, -1.3380769 ],
       [-0.41973367,  0.13818263,         nan, -0.99689243, -0.77245693],
       [ 0.05814555, -0.39934103, -1.34054513, -0.37344873, -0.39647018],
       [ 0.16616133, -0.31043135, -1.55789839, -0.01650516,  0.43836922],
       [-0.43014611, -0.34297541, -1.34905813,         nan,  0.13111302]])

In [8]:
np.isnan(a)

array([[False, False, False, False, False],
       [False, False,  True, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False,  True, False]])

In [9]:
np.nanmean(a)

-0.3424491807573146

In [10]:
a[np.isnan(a)] = 0
a

array([[ 0.90372471,  1.4731846 , -0.57945294, -0.56177974, -1.3380769 ],
       [-0.41973367,  0.13818263,  0.        , -0.99689243, -0.77245693],
       [ 0.05814555, -0.39934103, -1.34054513, -0.37344873, -0.39647018],
       [ 0.16616133, -0.31043135, -1.55789839, -0.01650516,  0.43836922],
       [-0.43014611, -0.34297541, -1.34905813,  0.        ,  0.13111302]])

### Algèbre linéaire

In [11]:
a = np.ones((2,3))
b = np.ones((3,2))
a, b

(array([[1., 1., 1.],
        [1., 1., 1.]]),
 array([[1., 1.],
        [1., 1.],
        [1., 1.]]))

In [12]:
a.T

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [13]:
c = np.random.randint(0,10, [3,3])
print(c)
np.linalg.det(c)

[[6 0 3]
 [7 3 3]
 [6 6 3]]


18.000000000000004

In [14]:
np.linalg.inv(c)

array([[-0.5       ,  1.        , -0.5       ],
       [-0.16666667,  0.        ,  0.16666667],
       [ 1.33333333, -2.        ,  1.        ]])

In [15]:
np.linalg.eig(c)

(array([11.34662278+0.j        ,  0.32668861+1.21640851j,
         0.32668861-1.21640851j]),
 array([[ 0.39638863+0.j        ,  0.43227919+0.09268451j,
          0.43227919-0.09268451j],
        [ 0.58635223+0.j        , -0.05130311-0.26603601j,
         -0.05130311+0.26603601j],
        [ 0.70644682+0.j        , -0.85506556+0.j        ,
         -0.85506556-0.j        ]]))

In [16]:
np.random.seed(0)
a = np.random.randint(0, 100, [10,5])
a

array([[44, 47, 64, 67, 67],
       [ 9, 83, 21, 36, 87],
       [70, 88, 88, 12, 58],
       [65, 39, 87, 46, 88],
       [81, 37, 25, 77, 72],
       [ 9, 20, 80, 69, 79],
       [47, 64, 82, 99, 88],
       [49, 29, 19, 19, 14],
       [39, 32, 65,  9, 57],
       [32, 31, 74, 23, 35]])

In [17]:
b = (a - np.mean(a,axis=0)) / np.std(a, axis=0)
b

array([[-0.02206157,  0.        ,  0.13173823,  0.72539252,  0.10755798],
       [-1.56637126,  1.61579632, -1.48676006, -0.33034307,  0.96802178],
       [ 1.12513992,  1.84021247,  1.03508612, -1.14768676, -0.27965074],
       [ 0.90452425, -0.35906585,  0.99744662,  0.0102168 ,  1.01104497],
       [ 1.6104944 , -0.44883231, -1.33620208,  1.0659524 ,  0.32267393],
       [-1.56637126, -1.21184724,  0.73397016,  0.7935045 ,  0.62383626],
       [ 0.11030784,  0.76301493,  0.80924915,  1.81518411,  1.01104497],
       [ 0.1985541 , -0.80789816, -1.56203905, -0.90929485, -2.17267111],
       [-0.24267724, -0.67324847,  0.16937773, -1.24985473, -0.32267393],
       [-0.55153918, -0.7181317 ,  0.50813319, -0.77307091, -1.26918412]])

In [18]:
b.mean(axis=0)

array([-2.22044605e-17, -4.44089210e-17,  0.00000000e+00, -1.22124533e-16,
       -4.44089210e-17])

In [19]:
b.std(axis=0)

array([1., 1., 1., 1., 1.])